import { chromium, BrowserContext } from 'playwright';
import { discordSelectors } from './discord-selectors.js';
import { assertAllowedDiscordChannelUrl } from './readonly-policy.js';
import { cleanMentions } from './message-payload.js';
export type CollectedMessage = { source: 'discord-web'; guildId?: string; channelId?: string; messageId?: string; author: { discordUserId?: string; displayName: string }; mentions: { discordUserId?: string; displayName: string }[]; text: string; timestamp: string; collectedAt: string; attachments: { filename?: string; contentType?: string; url?: string }[] };
export class DiscordWebAdapter {
  private context?: BrowserContext;
  async start(headless = true) { this.context = await chromium.launchPersistentContext('/data/discord-profile', { headless }); }
  async stop() { await this.context?.close(); }
  async readChannel(url: string, cutoff: Date): Promise<CollectedMessage[]> { if (!this.context) throw new Error('Browser context is not started'); const channelUrl = assertAllowedDiscordChannelUrl(url); const [, guildId, channelId] = channelUrl.pathname.match(/^\/channels\/(\d+)\/(\d+)$/) ?? []; if (!guildId || !channelId) throw new Error('Invalid Discord channel URL'); const page = await this.context.newPage(); await page.goto(channelUrl.toString(), { waitUntil: 'domcontentloaded' }); const messagesLocator = page.locator(discordSelectors.message); await messagesLocator.first().waitFor({ state: 'attached', timeout: 15000 }).catch(() => undefined); const hasChallenge = await page.locator('text=/captcha|verify|подтверд/i').count(); if (hasChallenge) throw new Error('AUTH_REQUIRED');
    let oldest = new Date(); let stalled = 0;
    for (let pass = 0; pass < 120 && oldest >= cutoff && stalled < 4; pass++) { const before = await page.evaluate(() => { const candidates = [...document.querySelectorAll<HTMLElement>('[class*="scroller"]')].filter((element) => element.scrollHeight > element.clientHeight && element.scrollTop >= 0).sort((left, right) => right.scrollHeight - left.scrollHeight); const scroller = candidates[0]; return scroller ? { top: scroller.scrollTop, height: scroller.scrollHeight } : null; }); const timestamps = await messagesLocator.locator(discordSelectors.timestamp).evaluateAll((nodes) => nodes.map((node) => node.getAttribute('datetime')).filter((value): value is string => Boolean(value))); const nextOldest = timestamps.length ? new Date(Math.min(...timestamps.map((value) => new Date(value).getTime()))) : oldest; if (nextOldest >= oldest && before?.top === 0) stalled++; else stalled = 0; oldest = nextOldest; if (oldest < cutoff) break; const moved = await page.evaluate(() => { const candidates = [...document.querySelectorAll<HTMLElement>('[class*="scroller"]')].filter((element) => element.scrollHeight > element.clientHeight && element.scrollTop >= 0).sort((left, right) => right.scrollHeight - left.scrollHeight); const scroller = candidates[0]; if (!scroller) return false; const previous = scroller.scrollTop; scroller.scrollTop = Math.max(0, previous - Math.max(600, scroller.clientHeight * 0.8)); return scroller.scrollTop !== previous; }); if (!moved && before?.top === 0) stalled++; await page.waitForTimeout(1000); }
    if (oldest >= cutoff) { await page.close(); throw new Error(`INCOMPLETE_HISTORY: reached ${oldest.toISOString()} before cutoff ${cutoff.toISOString()}`); }
    const messages = await messagesLocator.evaluateAll((nodes, selectors) => { let previousAuthor: { discordUserId?: string; displayName: string } | undefined; return nodes.flatMap((node) => { const time = node.querySelector(selectors.timestamp)?.getAttribute('datetime'); const authorNode = node.querySelector(selectors.author); const displayName = authorNode?.textContent?.trim(); const discordUserId = authorNode?.getAttribute('data-user-id') ?? node.getAttribute('data-message-author-id') ?? undefined; if (displayName) previousAuthor = discordUserId ? { displayName, discordUserId } : { displayName }; const text = node.querySelector(selectors.content)?.textContent?.trim() ?? ''; const content = node.querySelector(selectors.content); const mentions = content ? [...content.querySelectorAll(selectors.mention)].map((mention) => mention.textContent ?? '') : []; const attachments = [...node.querySelectorAll(selectors.attachment)].map((attachment) => ({ filename: attachment.getAttribute('download') ?? undefined, contentType: attachment.querySelector('img')?.getAttribute('src')?.includes('.gif') ? 'image/gif' : 'image/*', url: attachment.getAttribute('href') ?? undefined })); return time && previousAuthor ? [{ source: 'discord-web' as const, messageId: node.id.replace(/^chat-messages-/, '') || undefined, author: previousAuthor, mentions, text, timestamp: time, collectedAt: new Date().toISOString(), attachments }] : []; }); }, discordSelectors); await page.close(); return messages.filter((message) => new Date(message.timestamp) >= cutoff).map((message) => ({ ...message, mentions: cleanMentions(message.mentions), guildId, channelId })); }
  async readRecentChannel(url: string, cutoff: Date, limit = 20): Promise<CollectedMessage[]> { if (!this.context) throw new Error('Browser context is not started'); const channelUrl = assertAllowedDiscordChannelUrl(url); const [, guildId, channelId] = channelUrl.pathname.match(/^\/channels\/(\d+)\/(\d+)$/) ?? []; if (!guildId || !channelId) throw new Error('Invalid Discord channel URL'); const page = await this.context.newPage(); await page.goto(channelUrl.toString(), { waitUntil: 'domcontentloaded' }); const messagesLocator = page.locator(discordSelectors.message); await messagesLocator.first().waitFor({ state: 'attached', timeout: 15000 }).catch(() => undefined); if (await page.locator('text=/captcha|verify|подтверд/i').count()) throw new Error('AUTH_REQUIRED'); const messages = await messagesLocator.evaluateAll((nodes, selectors) => { let previousAuthor: { discordUserId?: string; displayName: string } | undefined; return nodes.flatMap((node) => { const time = node.querySelector(selectors.timestamp)?.getAttribute('datetime'); const authorNode = node.querySelector(selectors.author); const displayName = authorNode?.textContent?.trim(); const discordUserId = authorNode?.getAttribute('data-user-id') ?? node.getAttribute('data-message-author-id') ?? undefined; if (displayName) previousAuthor = discordUserId ? { displayName, discordUserId } : { displayName }; const content = node.querySelector(selectors.content); const mentions = content ? [...content.querySelectorAll(selectors.mention)].map((mention) => mention.textContent ?? '') : []; const attachments = [...node.querySelectorAll(selectors.attachment)].map((attachment) => ({ filename: attachment.getAttribute('download') ?? undefined, contentType: attachment.querySelector('img')?.getAttribute('src')?.includes('.gif') ? 'image/gif' : 'image/*', url: attachment.getAttribute('href') ?? undefined })); return time && previousAuthor ? [{ source: 'discord-web' as const, messageId: node.id.replace(/^chat-messages-/, '') || undefined, author: previousAuthor, mentions, text: content?.textContent?.trim() ?? '', timestamp: time, collectedAt: new Date().toISOString(), attachments }] : []; }); }, discordSelectors); await page.close(); return messages.filter((message) => new Date(message.timestamp) >= cutoff).sort((left, right) => new Date(right.timestamp).getTime() - new Date(left.timestamp).getTime()).slice(0, limit).map((message) => ({ ...message, mentions: cleanMentions(message.mentions), guildId, channelId })); }
}
