import { createHmac, randomUUID } from 'crypto';
import { DiscordWebAdapter } from './discord-web.adapter.js';
const baseUrl = process.env.BACKEND_INTERNAL_URL ?? 'http://backend:3001'; const configuredSecret = process.env.COLLECTOR_SHARED_SECRET;
if (!configuredSecret || Buffer.byteLength(configuredSecret) < 32) throw new Error('COLLECTOR_SHARED_SECRET must be at least 32 bytes');
const secret: string = configuredSecret;
async function signedFetch(path: string, init: RequestInit = {}) { const body = typeof init.body === 'string' ? init.body : ''; const timestamp = String(Date.now()); const requestId = randomUUID(); const signature = createHmac('sha256', secret).update(`${timestamp}.${requestId}.${body}`).digest('hex'); return fetch(`${baseUrl}${path}`, { ...init, headers: { ...init.headers, 'X-Collector-Timestamp': timestamp, 'X-Collector-Request-Id': requestId, 'X-Collector-Signature': signature } }); }
type Source = { id: string; name: string; channelUrl: string; lookbackDays: number | null };
type Config = { globalLookbackDays: number; sources: Source[] };
async function config(): Promise<Config> { const response = await signedFetch('/api/internal/collector/config'); if (!response.ok) throw new Error(`Config request failed: ${response.status}`); return response.json() as Promise<Config>; }
async function submit(sourceId: string, messages: unknown[]) { if (!messages.length) return; const response = await signedFetch('/api/internal/integrations/discord/messages', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sourceId, messages }) }); if (!response.ok) throw new Error(`Message submit failed: ${response.status}`); }
async function heartbeat(status: 'IDLE' | 'DEGRADED', lastError?: string) { const response = await signedFetch('/api/internal/collector/heartbeat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'discord-web', version: '0.1.0', status, lastError }) }); if (!response.ok) throw new Error(`Heartbeat failed: ${response.status}`); }
async function cycle() { try { const requestResponse = await signedFetch('/api/internal/collector/scan-requests/claim', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); if (!requestResponse.ok) throw new Error(`Scan request claim failed: ${requestResponse.status}`); const rawRequest = await requestResponse.text(); const request = rawRequest ? JSON.parse(rawRequest) as { id: string; sourceId?: string; recentDays: number; limit: number } : null; if (!request) { await heartbeat('IDLE'); return; } const value = await config(); const sources = request.sourceId ? value.sources.filter((source) => source.id === request.sourceId) : value.sources; const adapter = new DiscordWebAdapter(); await adapter.start(true); try { const results: { source: string; scanned: number; accepted: number }[] = []; for (const [index, source] of sources.entries()) { if (index) await new Promise((resolve) => setTimeout(resolve, 5000)); const messages = await adapter.readRecentChannel(source.channelUrl, new Date(Date.now() - request.recentDays * 86400000), request.limit); const response = await signedFetch('/api/internal/integrations/discord/messages', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sourceId: source.id, messages }) }); if (!response.ok) throw new Error(`Message submit failed: ${response.status}`); const result = await response.json() as { accepted: number }; results.push({ source: source.name, scanned: messages.length, accepted: result.accepted }); } await signedFetch(`/api/internal/collector/scan-requests/${request.id}/complete`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ result: results }) }); } catch (error) { const message = error instanceof Error ? error.message : 'Unknown collector error'; await signedFetch(`/api/internal/collector/scan-requests/${request.id}/fail`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ errorMessage: message }) }); throw error; } finally { await adapter.stop(); } await heartbeat('IDLE'); } catch (error) { const message = error instanceof Error ? error.message : 'Unknown collector error'; console.error(JSON.stringify({ event: 'collector.error', message })); try { await heartbeat('DEGRADED', message); } catch { /* Backend may be unavailable; retry at next cycle. */ } } }
void cycle(); setInterval(() => { void cycle(); }, 60000);
