CREATE TYPE "Role" AS ENUM ('EMPLOYEE', 'LEADER', 'ADMIN');
CREATE TYPE "SourceStatus" AS ENUM ('ACTIVE', 'PAUSED', 'ERROR', 'AUTH_REQUIRED');
CREATE TYPE "ParserMode" AS ENUM ('SEQUENCE_RANGE', 'TRAINING_MESSAGE', 'NOT_CONFIGURED');
CREATE TYPE "MessageStatus" AS ENUM ('PARSED', 'UNPARSED', 'UNKNOWN_EMPLOYEE', 'UNKNOWN_POSITION', 'UNKNOWN_DEPARTMENT', 'REVIEW_REQUIRED', 'DUPLICATE', 'SEQUENCE_GAP', 'SEQUENCE_CONFLICT', 'OUT_OF_WINDOW', 'ERROR');
CREATE TYPE "ActivitySourceType" AS ENUM ('DISCORD', 'MANUAL', 'IMPORT', 'API');

CREATE TABLE "Rank" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "shortName" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0, "active" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "Rank_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Position" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "shortName" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0, "active" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "Position_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Department" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "sortOrder" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "Department_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Employee" ("id" TEXT NOT NULL, "gameName" TEXT NOT NULL, "discordUserId" TEXT, "discordDisplayName" TEXT, "rankId" TEXT, "positionId" TEXT, "departmentId" TEXT, "positionRaw" TEXT, "manualPositionOverride" BOOLEAN NOT NULL DEFAULT false, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Employee_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL, "username" TEXT NOT NULL, "email" TEXT, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'EMPLOYEE', "employeeId" TEXT, "disabledAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" TIMESTAMP(3) NOT NULL, "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "userAgent" TEXT, "revokedAt" TIMESTAMP(3), CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PositionAlias" ("id" TEXT NOT NULL, "positionId" TEXT NOT NULL, "alias" TEXT NOT NULL, "normalizedAlias" TEXT NOT NULL, CONSTRAINT "PositionAlias_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmployeeAlias" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "source" TEXT NOT NULL, "alias" TEXT NOT NULL, "normalizedAlias" TEXT NOT NULL, CONSTRAINT "EmployeeAlias_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ActivityType" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "singularName" TEXT NOT NULL, "unitLabel" TEXT, "icon" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0, "active" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "ActivityType_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DiscordSource" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "channelUrl" TEXT NOT NULL, "guildId" TEXT NOT NULL, "channelId" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "parserMode" "ParserMode" NOT NULL DEFAULT 'NOT_CONFIGURED', "lookbackDays" INTEGER, "status" "SourceStatus" NOT NULL DEFAULT 'PAUSED', "lastCollectedAt" TIMESTAMP(3), "lastMessageTimestamp" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DiscordSource_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DiscordSourceRule" ("id" TEXT NOT NULL, "sourceId" TEXT NOT NULL, "activityTypeId" TEXT, "parserKey" TEXT NOT NULL, "priority" INTEGER NOT NULL DEFAULT 0, "enabled" BOOLEAN NOT NULL DEFAULT true, "parserConfig" JSONB NOT NULL DEFAULT '{}', CONSTRAINT "DiscordSourceRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IntegrationMessage" ("id" TEXT NOT NULL, "sourceId" TEXT NOT NULL, "source" TEXT NOT NULL, "sourceMessageId" TEXT, "guildId" TEXT, "channelId" TEXT, "authorDiscordId" TEXT, "authorRaw" TEXT NOT NULL, "textRaw" TEXT NOT NULL, "messageTimestamp" TIMESTAMP(3) NOT NULL, "collectedAt" TIMESTAMP(3) NOT NULL, "status" "MessageStatus" NOT NULL, "employeeId" TEXT, "parsedFrom" INTEGER, "parsedTo" INTEGER, "parsedQuantity" INTEGER, "fingerprint" TEXT NOT NULL, "parserVersion" TEXT NOT NULL DEFAULT '1', "errorCode" TEXT, "errorMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "IntegrationMessage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ActivityEvent" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "activityTypeId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "sourceType" "ActivitySourceType" NOT NULL, "sourceId" TEXT, "integrationMessageId" TEXT, "metadata" JSONB NOT NULL DEFAULT '{}', "createdBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ActivityEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SourceSequenceItem" ("id" TEXT NOT NULL, "sourceId" TEXT NOT NULL, "sequenceNumber" INTEGER NOT NULL, "integrationMessageId" TEXT NOT NULL, "employeeId" TEXT, "activityEventId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SourceSequenceItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CollectorInstance" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "version" TEXT NOT NULL, "lastHeartbeatAt" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL, "lastError" TEXT, CONSTRAINT "CollectorInstance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "userId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "oldValue" JSONB, "newValue" JSONB, "ip" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Rank_name_key" ON "Rank"("name");
CREATE UNIQUE INDEX "Position_name_key" ON "Position"("name");
CREATE UNIQUE INDEX "Department_code_key" ON "Department"("code");
CREATE UNIQUE INDEX "Employee_discordUserId_key" ON "Employee"("discordUserId");
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_employeeId_key" ON "User"("employeeId");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE UNIQUE INDEX "PositionAlias_normalizedAlias_key" ON "PositionAlias"("normalizedAlias");
CREATE UNIQUE INDEX "EmployeeAlias_source_normalizedAlias_key" ON "EmployeeAlias"("source", "normalizedAlias");
CREATE UNIQUE INDEX "ActivityType_code_key" ON "ActivityType"("code");
CREATE UNIQUE INDEX "DiscordSource_channelUrl_key" ON "DiscordSource"("channelUrl");
CREATE UNIQUE INDEX "IntegrationMessage_fingerprint_key" ON "IntegrationMessage"("fingerprint");
CREATE UNIQUE INDEX "IntegrationMessage_source_sourceMessageId_key" ON "IntegrationMessage"("source", "sourceMessageId");
CREATE UNIQUE INDEX "SourceSequenceItem_sourceId_sequenceNumber_key" ON "SourceSequenceItem"("sourceId", "sequenceNumber");
CREATE UNIQUE INDEX "CollectorInstance_name_key" ON "CollectorInstance"("name");

ALTER TABLE "Employee" ADD CONSTRAINT "Employee_rankId_fkey" FOREIGN KEY ("rankId") REFERENCES "Rank"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_positionId_fkey" FOREIGN KEY ("positionId") REFERENCES "Position"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PositionAlias" ADD CONSTRAINT "PositionAlias_positionId_fkey" FOREIGN KEY ("positionId") REFERENCES "Position"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeAlias" ADD CONSTRAINT "EmployeeAlias_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DiscordSourceRule" ADD CONSTRAINT "DiscordSourceRule_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DiscordSource"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DiscordSourceRule" ADD CONSTRAINT "DiscordSourceRule_activityTypeId_fkey" FOREIGN KEY ("activityTypeId") REFERENCES "ActivityType"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IntegrationMessage" ADD CONSTRAINT "IntegrationMessage_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DiscordSource"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ActivityEvent" ADD CONSTRAINT "ActivityEvent_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ActivityEvent" ADD CONSTRAINT "ActivityEvent_activityTypeId_fkey" FOREIGN KEY ("activityTypeId") REFERENCES "ActivityType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ActivityEvent" ADD CONSTRAINT "ActivityEvent_integrationMessageId_fkey" FOREIGN KEY ("integrationMessageId") REFERENCES "IntegrationMessage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SourceSequenceItem" ADD CONSTRAINT "SourceSequenceItem_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DiscordSource"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SourceSequenceItem" ADD CONSTRAINT "SourceSequenceItem_integrationMessageId_fkey" FOREIGN KEY ("integrationMessageId") REFERENCES "IntegrationMessage"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
