import { Body, Controller, Get, Injectable, Param, Patch, Post, UseGuards } from '@nestjs/common';
import { IsBoolean, IsEnum, IsInt, IsOptional, IsString, Length, Max, Min } from 'class-validator';
import { CountMode, ParserMode, Role } from '@prisma/client';
import { PrismaService } from './prisma.service';
import { RoleGuard, Roles, SessionGuard } from './auth';

class CreateSourceDto { @IsString() @Length(1, 120) name!: string; @IsString() @Length(1, 512) channelUrl!: string; @IsEnum(ParserMode) parserMode!: ParserMode; @IsEnum(CountMode) countMode!: CountMode; @IsOptional() @IsInt() @Min(1) @Max(30) lookbackDays?: number; @IsBoolean() enabled!: boolean; }
class CreateSourceRuleDto { @IsOptional() @IsString() activityTypeId?: string; @IsString() @Length(1, 100) parserKey!: string; @IsOptional() @IsInt() @Min(0) @Max(1000) priority = 0; @IsBoolean() enabled = true; }
class UpdateSourceDto { @IsOptional() @IsString() @Length(1, 120) name?: string; @IsOptional() @IsString() @Length(1, 512) channelUrl?: string; @IsOptional() @IsBoolean() confirmChannelChange?: boolean; @IsOptional() @IsEnum(ParserMode) parserMode?: ParserMode; @IsOptional() @IsEnum(CountMode) countMode?: CountMode; @IsOptional() @IsInt() @Min(1) @Max(30) lookbackDays?: number; @IsOptional() @IsBoolean() enabled?: boolean; @IsOptional() @IsString() activityTypeId?: string; }
function validateDiscordUrl(value: string) { const url = new URL(value); const parts = url.pathname.split('/').filter(Boolean); const allowedGuild = process.env.ALLOWED_DISCORD_GUILD_ID; if (url.protocol !== 'https:' || url.hostname !== 'discord.com' || parts.length !== 3 || parts[0] !== 'channels' || !/^\d+$/.test(parts[1]) || !/^\d+$/.test(parts[2]) || (allowedGuild && parts[1] !== allowedGuild)) throw new Error('Недопустимый URL Discord канала'); return { channelUrl: `https://discord.com/channels/${parts[1]}/${parts[2]}`, guildId: parts[1], channelId: parts[2] }; }
function validateModes(parserMode: ParserMode, countMode: CountMode) { if (countMode === 'LINES') throw new Error('Подсчет по строкам не используется. Выберите картинки или учебный текст.'); if (parserMode === 'TRAINING_MESSAGE' && countMode !== 'TRAINING_TEXT') throw new Error('Для экзаменов и лекций используйте текстовый режим'); if (parserMode === 'SEQUENCE_RANGE' && countMode === 'TRAINING_TEXT') throw new Error('Для числового канала используйте подсчет по картинкам'); }

@Injectable()
export class SourcesService {
  constructor(private readonly prisma: PrismaService) {}
  list() { return this.prisma.discordSource.findMany({ include: { rules: { include: { activityType: true }, orderBy: { priority: 'desc' } } }, orderBy: [{ guildId: 'asc' }, { name: 'asc' }] }); }
  async create(dto: CreateSourceDto) { const channel = validateDiscordUrl(dto.channelUrl); validateModes(dto.parserMode, dto.countMode); return this.prisma.discordSource.create({ data: { ...dto, ...channel, status: dto.enabled ? 'ACTIVE' : 'PAUSED' } }); }
  async update(sourceId: string, dto: UpdateSourceDto) {
    const source = await this.prisma.discordSource.findUniqueOrThrow({ where: { id: sourceId } }); const parserMode = dto.parserMode ?? source.parserMode; const countMode = dto.countMode ?? source.countMode; const channel = dto.channelUrl && dto.channelUrl !== source.channelUrl ? validateDiscordUrl(dto.channelUrl) : null;
    if (channel && !dto.confirmChannelChange) throw new Error('Подтвердите смену Discord-канала. История сообщений сохранит исходные идентификаторы каналов.'); validateModes(parserMode, countMode);
    return this.prisma.$transaction(async (tx) => { const updated = await tx.discordSource.update({ where: { id: sourceId }, data: { name: dto.name, channelUrl: channel?.channelUrl, guildId: channel?.guildId, channelId: channel?.channelId, parserMode: dto.parserMode, countMode: dto.countMode, lookbackDays: dto.lookbackDays, enabled: dto.enabled, status: dto.enabled === false ? 'PAUSED' : undefined }, include: { rules: true } }); if (channel) await tx.auditLog.create({ data: { action: 'DISCORD_SOURCE_CHANNEL_CHANGED', entityType: 'DiscordSource', entityId: sourceId, oldValue: { guildId: source.guildId, channelId: source.channelId }, newValue: channel } }); if (dto.activityTypeId && parserMode === 'SEQUENCE_RANGE') { const rule = updated.rules.find((item) => item.parserKey === 'SEQUENCE_RANGE'); if (rule) await tx.discordSourceRule.update({ where: { id: rule.id }, data: { activityTypeId: dto.activityTypeId } }); else await tx.discordSourceRule.create({ data: { sourceId, activityTypeId: dto.activityTypeId, parserKey: 'SEQUENCE_RANGE', priority: 100, enabled: true } }); } return updated; });
  }
  async addRule(sourceId: string, dto: CreateSourceRuleDto) { const source = await this.prisma.discordSource.findUniqueOrThrow({ where: { id: sourceId } }); if (source.parserMode === 'SEQUENCE_RANGE' && (!dto.activityTypeId || dto.parserKey !== 'SEQUENCE_RANGE')) throw new Error('Для числового канала требуется один вид активности и parserKey SEQUENCE_RANGE'); return this.prisma.discordSourceRule.create({ data: { sourceId, ...dto } }); }
}
@Controller('api/admin/discord-sources') @UseGuards(SessionGuard, RoleGuard) @Roles(Role.ADMIN)
export class SourcesController { constructor(private readonly sources: SourcesService) {} @Get() list() { return this.sources.list(); } @Post() create(@Body() dto: CreateSourceDto) { return this.sources.create(dto); } @Patch(':id') update(@Param('id') id: string, @Body() dto: UpdateSourceDto) { return this.sources.update(id, dto); } @Post(':id/rules') addRule(@Param('id') id: string, @Body() dto: CreateSourceRuleDto) { return this.sources.addRule(id, dto); } }
export { validateDiscordUrl };
